[forest]
trees = ["trees", "quark/trees"]                   # The directories in which your trees are stored
assets = ["assets", "quark/html"]                  # The directories in which your assets are stored
theme = "theme"                      # The directory in which your theme is stored
